apiVersion: v1
kind: Service
metadata:
  labels:
    app: contiamo-app
  name: contiamo-app
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path:   /metrics
      prometheus.io/port:   '8080'
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: contiamo-app