apiVersion: apps/v1
kind: Deployment
metadata:
  name: contiamo-app
  labels:
    app: contiamo-app
spec:
  selector:
    matchLabels:
      app: contiamo-app
      tier: web
  template:
    metadata:
      labels:
        app: contiamo-app
        tier: web
    spec:
      containers:
      - name: contiamo-app
        image: gcr.io/t-dragon-246512/contiamo-app:v2
        env:
          - name: PGPASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres
                key: password
          - name: DB_HOST
            value: postgres
        ports:
        - containerPort: 8080