apiVersion: v1
kind: Service
metadata:
  labels:
    app: jmx-exporter
  name: jmx-exporter
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path:   /metrics
      prometheus.io/port:   '5556'
spec:
  type: ClusterIP
  ports:
    - port: 5556
  selector:
    app: jmx-exporter