apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: "default"
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path:   /
      prometheus.io/port:   '3000'

spec:
  type: LoadBalancer
  selector:
    component: grafana
  ports:
  - port: 3000
    targetPort: 3000