apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  type: ClusterIP # for the Service, as this value makes the Service reachable only from within the cluster.
  ports:
    - port: 5432
  selector:
    app: postgres